// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHBjmSMGTMdYtCIYgJDvYjI1ls8xPD0ps',
    appId: '1:180141803743:web:d8240efc5ba21f5599016a',
    messagingSenderId: '180141803743',
    projectId: 'omnizonaa',
    authDomain: 'omnizonaa.firebaseapp.com',
    storageBucket: 'omnizonaa.firebasestorage.app',
    measurementId: 'G-3F8MLG5VLD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxma0N2_X4Rit2DWZmjXGCmUE708mljlU',
    appId: '1:180141803743:android:c8d5abaabcdfd59d99016a',
    messagingSenderId: '180141803743',
    projectId: 'omnizonaa',
    storageBucket: 'omnizonaa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzRKQU4mAM1knWovzBmQn_BELJqWQEIMk',
    appId: '1:180141803743:ios:e5cedae418dda50399016a',
    messagingSenderId: '180141803743',
    projectId: 'omnizonaa',
    storageBucket: 'omnizonaa.firebasestorage.app',
    iosBundleId: 'com.example.pi3010104',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzRKQU4mAM1knWovzBmQn_BELJqWQEIMk',
    appId: '1:180141803743:ios:e5cedae418dda50399016a',
    messagingSenderId: '180141803743',
    projectId: 'omnizonaa',
    storageBucket: 'omnizonaa.firebasestorage.app',
    iosBundleId: 'com.example.pi3010104',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHBjmSMGTMdYtCIYgJDvYjI1ls8xPD0ps',
    appId: '1:180141803743:web:9cd3fff934409f5299016a',
    messagingSenderId: '180141803743',
    projectId: 'omnizonaa',
    authDomain: 'omnizonaa.firebaseapp.com',
    storageBucket: 'omnizonaa.firebasestorage.app',
    measurementId: 'G-5QDJ060R56',
  );

}